siteName: Annamorphose coaching
productionUrl: https://www.annamorphose.be
logo: /_images/annamorphose-logo-doc.webp
htmlHead: ''
cssHead: ''
languages:
  - code: fr
    status: published
    keepUrlPrefix: false
  - code: hu
    status: published
    keepUrlPrefix: false
collections:
  - services
  - reviews
